### ISSUE TITLE
Add documentation on how to use kine

### ISSUE THREAD

**Issue by afbjorklund** [afbjorklund/buildroot4kubernetes#23]
It is possible to use `kine` instead of `etcd`, in k8s.

This allows using a SQL database, such as sqlite.

```
kubeadm init --config kubeadm-master.cfg --ignore-preflight-errors ExternalEtcdVersion
```

The main issue is with generating the certificates...

-----

https://github.com/rancher/kine

> _Can be ran standalone so any k8s (not just k3s) can use Kine_

```yaml
etcd:
  external:
    endpoints:
    - http://k3s:2379
    caFile: ./ca.crt
    certFile: ./server.crt
    keyFile: ./server.key
```

[Minimal example of using kine](https://github.com/k3s-io/kine/blob/master/examples/minimal.md)
